{% set name = "pyserver" %}
{% set version = "1.1.1" %}

package:
   name: "{{ name }}"
   version: "{{ version }}"

source:
   url: http://software.igwn.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
   sha256: 1efb4a4c087b4eb21b281c4ebd470d3a0340e03a17473dd7ecb9420650347712

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - pip
    - python >=2.7
    - setuptools
  run:
    - python >=2.7
    - pythonvirgotools
    - pytango

test:
  imports:
    - pyserver

about:
  home: "https://git.ligo.org/virgo/virgoapp/pyserver"
  license: "GPL-2.0-or-later"
  license_family: "GPL"
  license_file: "LICENSE"
  summary:
    pyserver is a tool to run a custom python server that is fdio compliant

extra:
  recipe-maintainers:
      - rhyspoulton
      - fcarbogn 
